export const OneTableSchema = {
  format: 'onetable:1.1.0',
  version: '0.0.1',
  indexes: {
    primary: { hash: 'pk', sort: 'sk' },
    gs1: { hash: 'gs1pk', sort: 'gs1sk', project: 'all' },
    gsi2: { hash: 'cognitoId' },
  },
  models: {
    Product: {
      pk: { type: String, value: 'PRODUCT#${id}' },
      sk: { type: String, value: 'PRODUCT#${id}' },
      id: { type: String, required: true, generate: 'uuid' },
      name: { type: String, required: true },
      sku: { type: String, required: true },
      description: { type: String },
      price: { type: Number, required: true },
      quantity: { type: Number, required: true },
      organizationId: { type: String, required: true },
      createdAt: { type: Number, required: true },
      updatedAt: { type: Number, required: true },
      gs1pk: { type: String, value: 'ORGANIZATION#${organizationId}#PRODUCTS' },
      gs1sk: { type: String, value: 'PRODUCT#${createdAt}' },
    },
    StockMovement: {
      pk: { type: String, value: 'PRODUCT#${productId}' },
      sk: { type: String, value: 'STOCK#${createdAt}#${id}' },
      id: { type: String, required: true, generate: 'uuid' },
      productId: { type: String, required: true },
      type: { type: String, required: true },
      quantity: { type: Number, required: true },
      reason: { type: String },
      performedBy: { type: String, required: true },
      organizationId: { type: String, required: true },
      createdAt: { type: String, required: true },
      gs1pk: { type: String, value: 'ORGANIZATION#${organizationId}#STOCKS' },
      gs1sk: { type: String, value: 'STOCK#${createdAt}' },
    },
    User: {
      pk: { type: String, value: 'USER#${id}' },
      sk: { type: String, value: 'USER#${id}' },
      id: { type: String, required: true, generate: 'uuid' },
      email: { type: String, required: true },
      name: { type: String, required: true },
      role: { type: String, required: true },
      cognitoId: { type: String, required: true },
      createdAt: { type: Number, required: true },
      updatedAt: { type: Number, required: true },
      gs1pk: { type: String, value: 'USERS' },
      gs1sk: { type: String, value: 'USER#${email}' },
    },
    Organization: {
      pk: { type: String, value: 'ORGANIZATION#${id}' },
      sk: { type: String, value: 'ORGANIZATION#${id}' },
      id: { type: String, required: true, generate: 'uuid' },
      name: { type: String, required: true },
      leaderId: { type: String, required: true },
      createdAt: { type: Number, required: true },
      updatedAt: { type: Number, required: true },
      gs1pk: { type: String, value: 'ORGANIZATIONS' },
      gs1sk: { type: String, value: 'ORGANIZATION#${name}' },
      // Subscription fields
      subscriptionStatus: {
        type: String,
        required: true,
        enum: ['trial', 'active', 'past_due', 'cancelled', 'expired'],
        default: 'trial',
      },
      trialStartDate: { type: Number, required: true },
      trialEndDate: { type: Number, required: true },
      // Polar.sh integration
      polarCustomerId: { type: String },
      polarSubscriptionId: { type: String },
      polarCheckoutId: { type: String },
      // Seat management
      seatCount: { type: Number, required: true, default: 5 },
      baseSeatCount: { type: Number, required: true, default: 5 },
      additionalSeats: { type: Number, required: true, default: 0 },
      // Billing period
      currentPeriodStart: { type: Number },
      currentPeriodEnd: { type: Number },
      cancelAtPeriodEnd: { type: Boolean, default: false },
    },
    OrganizationMember: {
      pk: { type: String, value: 'ORGANIZATION#${organizationId}' },
      sk: { type: String, value: 'USER#${userId}' },
      organizationId: { type: String, required: true },
      userId: { type: String, required: true },
      role: { type: String, required: true, enum: ['leader', 'member', 'pending'] },
      status: { type: String, required: true, enum: ['active', 'inactive', 'pending'] },
      createdAt: { type: Number, required: true },
      updatedAt: { type: Number, required: true },
      gs1pk: { type: String, value: 'USER#${userId}' },
      gs1sk: { type: String, value: 'ORGANIZATION#${organizationId}' },
    },
    OrganizationInvitation: {
      pk: { type: String, value: 'INVITATION#${token}' },
      sk: { type: String, value: 'INVITATION' },
      token: { type: String, required: true },
      organizationId: { type: String, required: true },
      email: { type: String, required: true },
      role: { type: String, required: true, enum: ['leader', 'member', 'pending'] },
      expiresAt: { type: Number, required: true, ttl: true },
      gs1pk: { type: String, value: 'ORGANIZATION#${organizationId}#INVITATIONS' },
      gs1sk: { type: String, value: 'INVITATION#${email}' },
    },
    Subscription: {
      pk: { type: String, value: 'ORGANIZATION#${organizationId}' },
      sk: { type: String, value: 'SUBSCRIPTION#${createdAt}#${id}' },
      id: { type: String, required: true, generate: 'uuid' },
      organizationId: { type: String, required: true },
      polarSubscriptionId: { type: String, required: true },
      polarCustomerId: { type: String, required: true },
      polarCheckoutId: { type: String },
      status: { type: String, required: true, enum: ['active', 'past_due', 'cancelled', 'expired'] },
      baseSeatCount: { type: Number, required: true },
      additionalSeats: { type: Number, required: true },
      totalSeats: { type: Number, required: true },
      basePrice: { type: Number, required: true },
      additionalSeatPrice: { type: Number, required: true },
      totalPrice: { type: Number, required: true },
      currency: { type: String, required: true, default: 'EUR' },
      currentPeriodStart: { type: Number, required: true },
      currentPeriodEnd: { type: Number, required: true },
      cancelAtPeriodEnd: { type: Boolean, default: false },
      createdAt: { type: Number, required: true },
      updatedAt: { type: Number, required: true },
      gs1pk: { type: String, value: 'SUBSCRIPTIONS' },
      gs1sk: { type: String, value: 'SUBSCRIPTION#${createdAt}' },
    },
    PolarWebhookEvent: {
      pk: { type: String, value: 'WEBHOOK#POLAR' },
      sk: { type: String, value: 'EVENT#${eventId}' },
      eventId: { type: String, required: true },
      eventType: { type: String, required: true },
      payload: { type: Object, required: true },
      processed: { type: Boolean, required: true, default: false },
      processedAt: { type: Number },
      error: { type: String },
      createdAt: { type: Number, required: true },
      gs1pk: { type: String, value: 'WEBHOOK_EVENTS' },
      gs1sk: { type: String, value: 'EVENT#${createdAt}' },
    },
  },
} as const;
