export const OneTableSchema = {
  format: 'onetable:1.1.0',
  version: '0.0.1',
  indexes: {
    primary: { hash: 'pk', sort: 'sk' },
    gs1: { hash: 'gs1pk', sort: 'gs1sk', project: 'all' },
    gsi2: { hash: 'cognitoId' },
  },
  models: {
    Product: {
      pk: { type: String, value: 'PRODUCT#${id}' },
      sk: { type: String, value: 'PRODUCT#${id}' },
      id: { type: String, required: true, generate: 'uuid' },
      name: { type: String, required: true },
      sku: { type: String, required: true },
      description: { type: String },
      price: { type: Number, required: true },
      quantity: { type: Number, required: true },
      createdAt: { type: Number, required: true },
      updatedAt: { type: Number, required: true },
      gs1pk: { type: String, value: 'PRODUCTS' },
      gs1sk: { type: String, value: 'PRODUCT#${createdAt}' },
    },
    StockMovement: {
      pk: { type: String, value: 'PRODUCT#${productId}' },
      sk: { type: String, value: 'STOCK#${createdAt}#${id}' },
      id: { type: String, required: true, generate: 'uuid' },
      productId: { type: String, required: true },
      type: { type: String, required: true },
      quantity: { type: Number, required: true },
      reason: { type: String },
      performedBy: { type: String, required: true },
      createdAt: { type: String, required: true },
      gs1pk: { type: String, value: 'STOCKS' },
      gs1sk: { type: String, value: 'STOCK#${createdAt}' },
    },
    User: {
      pk: { type: String, value: 'USER#${id}' },
      sk: { type: String, value: 'USER#${id}' },
      id: { type: String, required: true, generate: 'uuid' },
      email: { type: String, required: true },
      name: { type: String, required: true },
      role: { type: String, required: true },
      cognitoId: { type: String, required: true },
      createdAt: { type: Number, required: true },
      updatedAt: { type: Number, required: true },
      gs1pk: { type: String, value: 'USERS' },
      gs1sk: { type: String, value: 'USER#${email}' },
    },
  },
} as const;
